### ISSUE TITLE
not working with python 3 (urlparse dependency not include in python3 like this)

### ISSUE THREAD

**Issue by Nic01as** [nanvel/tornado-botocore#10]
new 1.2 version use "from urlparse import urlparse" in base.py line 4

in python 3, you need to use:
from urllib.parse import urlparse

if you use python3, you need to install 1.0.2 or fix this error : 
pip3 install tornado-botocore==1.0.2

**Comment by nanvel** [comment]
Fixed in v 1.1.1.
