### ISSUE TITLE
botocore==1.2.0 is hard dependency

### ISSUE THREAD

**Issue by martinhoefling** [nanvel/tornado-botocore#8]
Therefore, it is not installable together with e.g. boto3 which requires >=1.3.29

**Comment by dianasoare** [comment]
Are there any plans to support newer versions of `botocore` (right now at version 1.5.28) ? 

Thanks!

**Comment by massipasquesi** [comment]
I'm agree . I have to choise between use aws-cli that depends on botocore==1.5.32 and tc_aws using tornafo-botocore that depends on botocore==1.2.0.
Cannot use both together !!!

**Comment by massipasquesi** [comment]
I've forked this repository to try to resolve dependencies problems : 
https://github.com/thumbor-community/aws/issues/62#issuecomment-290712880

**Comment by massipasquesi** [comment]
Finding an easier solution ... like create a botocore-1.2 package ... but in botocore i found referencies to him self ... so ...

**Comment by nanvel** [comment]
Currently, I don't use it, and busy with other things.
So, probably, it will be broken until someone else (who need it) fix it. Send me a PR, and I'll find time to test and publish a new version.

**Comment by nanvel** [comment]
botocore version was updated to `botocore>=1.2,<1.6`.
